import { Property, TeamMember, Testimonial } from './types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Moradia de Luxo com Piscina em Valença',
    price: 450000,
    location: 'Valença, Viana do Castelo',
    type: 'Moradia',
    status: 'Venda',
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    description: 'Esta magnífica moradia de arquitetura contemporânea oferece o equilíbrio perfeito entre luxo e conforto. Situada numa zona tranquila de Valença, conta com acabamentos de alta qualidade, uma cozinha totalmente equipada e uma área exterior com piscina privativa.',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1200',
    ],
    features: ['Piscina', 'Jardim', 'Garagem', 'Ar Condicionado', 'Painéis Solares'],
    labels: ['Premium', 'Destaque'],
    energyRating: 'A+',
  },
  {
    id: '2',
    title: 'Apartamento T3 Moderno no Centro',
    price: 220000,
    location: 'Centro, Valença',
    type: 'Apartamento',
    status: 'Venda',
    bedrooms: 3,
    bathrooms: 2,
    area: 145,
    description: 'Apartamento T3 localizado no coração de Valença. Recentemente renovado com materiais premium, oferece vistas desafogadas sobre a cidade e proximidade a todos os serviços essenciais.',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=1200',
    ],
    features: ['Varanda', 'Elevador', 'Suite', 'Cozinha Equipada'],
    labels: ['Novo', 'Oportunidade'],
    energyRating: 'A',
  },
  {
    id: '3',
    title: 'Quinta Histórica no Alto Minho',
    price: 850000,
    location: 'Arredores, Valença',
    type: 'Moradia',
    status: 'Venda',
    bedrooms: 6,
    bathrooms: 4,
    area: 520,
    description: 'Propriedade única com história e charme. Esta quinta secular foi cuidadosamente restaurada, mantendo a traça original mas incorporando todas as comodidades modernas. Ideal para turismo rural ou residência de luxo.',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=1200',
    ],
    features: ['Terreno Amplo', 'Adega', 'Capela', 'Vistas Rio'],
    labels: ['Premium', 'Investimento'],
    energyRating: 'B',
  },
  {
    id: '4',
    title: 'Terreno para Construção com Vista Rio',
    price: 950000,
    location: 'Friestas, Valença',
    type: 'Terreno',
    status: 'Venda',
    area: 2500,
    description: 'Excelente terreno com viabilidade de construção para moradia unifamiliar. Localização privilegiada com vistas panorâmicas sobre o Rio Minho.',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=1200',
    ],
    features: ['Vista Rio', 'Acesso Alcatroado', 'Infraestruturas Próximas'],
    labels: ['Oportunidade'],
    energyRating: 'A',
  },
];

export const MOCK_TEAM: TeamMember[] = [
  {
    id: '1',
    name: 'Ricardo Silva',
    role: 'Diretor Comercial',
    bio: 'Com mais de 15 anos de experiência no mercado imobiliário do Alto Minho, o Ricardo lidera a equipa com foco na excelência e resultados.',
    photo: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=400',
    email: 'ricardo.silva@foxriver.pt',
    phone: '+351 912 345 678',
    whatsapp: '351912345678',
  },
  {
    id: '2',
    name: 'Ana Martins',
    role: 'Consultora Senior',
    bio: 'Especialista em imóveis premium e atendimento personalizado. A Ana garante que cada cliente encontra a casa dos seus sonhos.',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    email: 'ana.martins@foxriver.pt',
    phone: '+351 912 345 679',
    whatsapp: '351912345679',
  },
  {
    id: '3',
    name: 'João Pereira',
    role: 'Especialista em Investimento',
    bio: 'O João foca-se em oportunidades de investimento e análise de mercado, ajudando investidores a maximizar os seus retornos.',
    photo: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400',
    email: 'joao.pereira@foxriver.pt',
    phone: '+351 912 345 680',
    whatsapp: '351912345680',
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Maria Santos',
    text: 'Excelente acompanhamento na venda da minha casa. Profissionalismo e rapidez acima da média.',
    rating: 5,
    date: 'Janeiro 2024',
  },
  {
    id: '2',
    name: 'Carlos Mendes',
    text: 'A equipa da Fox River ajudou-me em todo o processo de crédito habitação. Recomendo vivamente.',
    rating: 5,
    date: 'Fevereiro 2024',
  },
];
